// Code generated by "stringer -type=FullscreenModeType"; DO NOT EDIT.

package ipc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoneFullscreenMode-0]
	_ = x[WorkspaceFullscreenMode-1]
	_ = x[GlobalFullscreenMode-2]
}

const _FullscreenModeType_name = "NoneFullscreenModeWorkspaceFullscreenModeGlobalFullscreenMode"

var _FullscreenModeType_index = [...]uint8{0, 18, 41, 61}

func (i FullscreenModeType) String() string {
	if i >= FullscreenModeType(len(_FullscreenModeType_index)-1) {
		return "FullscreenModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FullscreenModeType_name[_FullscreenModeType_index[i]:_FullscreenModeType_index[i+1]]
}
