// Code generated by "stringer -type=payloadType"; DO NOT EDIT.

package ipc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[runCommandMessage-0]
	_ = x[getWorkspacesMessage-1]
	_ = x[subscribeMessage-2]
	_ = x[getOutputsMessage-3]
	_ = x[getTreeMessage-4]
	_ = x[getMarksMessage-5]
	_ = x[getBarConfigMessage-6]
	_ = x[getVersionMessage-7]
	_ = x[getBindingModesMessage-8]
	_ = x[getConfigMessage-9]
	_ = x[sendTickMessage-10]
	_ = x[syncMessage-11]
	_ = x[getBindingStateMessage-12]
	_ = x[getInputsMessage-100]
	_ = x[getSeatsMessage-101]
}

const (
	_payloadType_name_0 = "runCommandMessagegetWorkspacesMessagesubscribeMessagegetOutputsMessagegetTreeMessagegetMarksMessagegetBarConfigMessagegetVersionMessagegetBindingModesMessagegetConfigMessagesendTickMessagesyncMessagegetBindingStateMessage"
	_payloadType_name_1 = "getInputsMessagegetSeatsMessage"
)

var (
	_payloadType_index_0 = [...]uint8{0, 17, 37, 53, 70, 84, 99, 118, 135, 157, 173, 188, 199, 221}
	_payloadType_index_1 = [...]uint8{0, 16, 31}
)

func (i payloadType) String() string {
	switch {
	case i <= 12:
		return _payloadType_name_0[_payloadType_index_0[i]:_payloadType_index_0[i+1]]
	case 100 <= i && i <= 101:
		i -= 100
		return _payloadType_name_1[_payloadType_index_1[i]:_payloadType_index_1[i+1]]
	default:
		return "payloadType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
