// Code generated by "stringer -type=PayloadType"; DO NOT EDIT.

package ipc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunCommandMessage-0]
	_ = x[GetWorkspacesMessage-1]
	_ = x[SubscribeMessage-2]
	_ = x[GetOutputsMessage-3]
	_ = x[GetTreeMessage-4]
	_ = x[GetMarksMessage-5]
	_ = x[GetBarConfigMessage-6]
	_ = x[GetVersionMessage-7]
	_ = x[GetBindingModesMessage-8]
	_ = x[GetConfigMessage-9]
	_ = x[SendTickMessage-10]
	_ = x[SyncMessage-11]
	_ = x[GetBindingStateMessage-12]
	_ = x[GetInputsMessage-100]
	_ = x[GetSeatsMessage-101]
	_ = x[WorkspaceEvent-2147483648]
	_ = x[ModeEvent-2147483650]
	_ = x[WindowEvent-2147483651]
	_ = x[BarconfigUpdateEvent-2147483652]
	_ = x[BindingEvent-2147483653]
	_ = x[ShutdownEvent-2147483654]
	_ = x[TickEvent-2147483655]
	_ = x[BarStatusUpdateEvent-2147483668]
	_ = x[InputEvent-2147483669]
}

const (
	_PayloadType_name_0 = "RunCommandMessageGetWorkspacesMessageSubscribeMessageGetOutputsMessageGetTreeMessageGetMarksMessageGetBarConfigMessageGetVersionMessageGetBindingModesMessageGetConfigMessageSendTickMessageSyncMessageGetBindingStateMessage"
	_PayloadType_name_1 = "GetInputsMessageGetSeatsMessage"
	_PayloadType_name_2 = "WorkspaceEvent"
	_PayloadType_name_3 = "ModeEventWindowEventBarconfigUpdateEventBindingEventShutdownEventTickEvent"
	_PayloadType_name_4 = "BarStatusUpdateEventInputEvent"
)

var (
	_PayloadType_index_0 = [...]uint8{0, 17, 37, 53, 70, 84, 99, 118, 135, 157, 173, 188, 199, 221}
	_PayloadType_index_1 = [...]uint8{0, 16, 31}
	_PayloadType_index_3 = [...]uint8{0, 9, 20, 40, 52, 65, 74}
	_PayloadType_index_4 = [...]uint8{0, 20, 30}
)

func (i PayloadType) String() string {
	switch {
	case i <= 12:
		return _PayloadType_name_0[_PayloadType_index_0[i]:_PayloadType_index_0[i+1]]
	case 100 <= i && i <= 101:
		i -= 100
		return _PayloadType_name_1[_PayloadType_index_1[i]:_PayloadType_index_1[i+1]]
	case i == 2147483648:
		return _PayloadType_name_2
	case 2147483650 <= i && i <= 2147483655:
		i -= 2147483650
		return _PayloadType_name_3[_PayloadType_index_3[i]:_PayloadType_index_3[i+1]]
	case 2147483668 <= i && i <= 2147483669:
		i -= 2147483668
		return _PayloadType_name_4[_PayloadType_index_4[i]:_PayloadType_index_4[i+1]]
	default:
		return "PayloadType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
