// Code generated by "stringer -type=LogLevel"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultLog-0]
	_ = x[InfoLog-10]
	_ = x[DebugLog-30]
}

const (
	_LogLevel_name_0 = "DefaultLog"
	_LogLevel_name_1 = "InfoLog"
	_LogLevel_name_2 = "DebugLog"
)

func (i LogLevel) String() string {
	switch {
	case i == 0:
		return _LogLevel_name_0
	case i == 10:
		return _LogLevel_name_1
	case i == 30:
		return _LogLevel_name_2
	default:
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
