// Code generated by "stringer -type=WinMgr"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WinMgrSway-0]
	_ = x[WinMgrI3-1]
}

const _WinMgr_name = "WinMgrSwayWinMgrI3"

var _WinMgr_index = [...]uint8{0, 10, 18}

func (i WinMgr) String() string {
	if i < 0 || i >= WinMgr(len(_WinMgr_index)-1) {
		return "WinMgr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WinMgr_name[_WinMgr_index[i]:_WinMgr_index[i+1]]
}
