// Code generated by "stringer -type=EventPayloadType"; DO NOT EDIT.

package ipc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WorkspaceEvent-2147483648]
	_ = x[ModeEvent-2147483650]
	_ = x[WindowEvent-2147483651]
	_ = x[BarconfigUpdateEvent-2147483652]
	_ = x[BindingEvent-2147483653]
	_ = x[ShutdownEvent-2147483654]
	_ = x[TickEvent-2147483655]
	_ = x[BarStateUpdateEvent-2147483668]
	_ = x[InputEvent-2147483669]
}

const (
	_EventPayloadType_name_0 = "WorkspaceEvent"
	_EventPayloadType_name_1 = "ModeEventWindowEventBarconfigUpdateEventBindingEventShutdownEventTickEvent"
	_EventPayloadType_name_2 = "BarStateUpdateEventInputEvent"
)

var (
	_EventPayloadType_index_1 = [...]uint8{0, 9, 20, 40, 52, 65, 74}
	_EventPayloadType_index_2 = [...]uint8{0, 19, 29}
)

func (i EventPayloadType) String() string {
	switch {
	case i == 2147483648:
		return _EventPayloadType_name_0
	case 2147483650 <= i && i <= 2147483655:
		i -= 2147483650
		return _EventPayloadType_name_1[_EventPayloadType_index_1[i]:_EventPayloadType_index_1[i+1]]
	case 2147483668 <= i && i <= 2147483669:
		i -= 2147483668
		return _EventPayloadType_name_2[_EventPayloadType_index_2[i]:_EventPayloadType_index_2[i+1]]
	default:
		return "EventPayloadType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
