// Code generated by "stringer -type=PayloadType"; DO NOT EDIT.

package ipc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunCommandMessage-0]
	_ = x[GetWorkspacesMessage-1]
	_ = x[SubscribeMessage-2]
	_ = x[GetOutputsMessage-3]
	_ = x[GetTreeMessage-4]
	_ = x[GetMarksMessage-5]
	_ = x[GetBarConfigMessage-6]
	_ = x[GetVersionMessage-7]
	_ = x[GetBindingModesMessage-8]
	_ = x[GetConfigMessage-9]
	_ = x[SendTickMessage-10]
	_ = x[SyncMessage-11]
	_ = x[GetBindingStateMessage-12]
	_ = x[GetInputsMessage-100]
	_ = x[GetSeatsMessage-101]
}

const (
	_PayloadType_name_0 = "runCommandMessagegetWorkspacesMessagesubscribeMessagegetOutputsMessagegetTreeMessagegetMarksMessagegetBarConfigMessagegetVersionMessagegetBindingModesMessagegetConfigMessagesendTickMessagesyncMessagegetBindingStateMessage"
	_PayloadType_name_1 = "getInputsMessagegetSeatsMessage"
)

var (
	_PayloadType_index_0 = [...]uint8{0, 17, 37, 53, 70, 84, 99, 118, 135, 157, 173, 188, 199, 221}
	_PayloadType_index_1 = [...]uint8{0, 16, 31}
)

func (i PayloadType) String() string {
	switch {
	case i <= 12:
		return _PayloadType_name_0[_PayloadType_index_0[i]:_PayloadType_index_0[i+1]]
	case 100 <= i && i <= 101:
		i -= 100
		return _PayloadType_name_1[_PayloadType_index_1[i]:_PayloadType_index_1[i+1]]
	default:
		return "PayloadType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
